### ISSUE TITLE
ticket merge issue

### ISSUE THREAD

**Issue by csskysea** [ivaldi/brimir#347] opened 2017-02-27 05:44 UTC
![image](https://cloud.githubusercontent.com/assets/3860974/23349921/c895fd04-fcf1-11e6-97b1-a04fdc122e85.png)
when merge two tickets ,the merged ticket's title would be the same with the ticket which commit first.but when you click the attachment(in ticket which commit latter originally) ,it will pop web page like attachment.

**Comment by frenkel** [comment] 2017-02-27 16:30
You mean that the attachment on the second ticket cannot be opened? Can it be opened on the original tickets' page?

**Comment by fiedl** [comment] 2017-02-27 21:00
I've seen this in production once, but haven't been able to track it down. 

The curious thing is that there is already a unit test for that.
https://github.com/ivaldi/brimir/blob/master/test/models/merged_ticket_test.rb#L66

Can this be reproduced?

**Comment by csskysea** [comment] 2017-02-28 01:25
of course，it can be reproduced, assume there are two tickets : a and b, a is old then b, we merged ticket a and ticket b, get new ticket a, and new ticket a contains all reply which original from old a and old b, if you want to download attachment from one reply which original from old b, it will report error.

**Comment by frenkel** [comment] 2017-02-28 08:52
@fiedl Maybe he means that second ticket doesn't have an attachment anymore? I don't think the test checks for that.

**Comment by csskysea** [comment] 2017-03-01 01:23
@frenkel yes,you are right.

**Comment by fiedl** [comment] 2017-03-05 10:45
I've done some checking:

### Steps to reproduce

1. Create "Ticket A" with attachment.
1. Create "Reply 1 to Ticket A" with attachment.
1. Create "Ticket B" with attachment.
1. Create "Reply 1 to Ticket B" with attachment.
1. Merge "Ticket A" and "Ticket B".

### Which attachments are accessible?

In the merged ticket,

- (i) [ok]✓ the attachment of "Ticket A" is accessible,
- (ii) [ok] the attachment of "Reply 1 to Ticket A" is accessible,
- (iii) **[fail] the attachment of "Ticket B" raises "ActiveRecord::RecordNotFound in AttachmentsController#show"**,
- (iv) [ok] the attachment of "Reply 1 to Ticket B" is accessible.

### What is tested already?

- (i) yes: `test 'merging tickets with attachments'`
- (ii) no
- (iii) yes: `test 'accessing attachment file for merged ticket'` 
- (iv) yes: `test 'accessing attachment file for merged reply'`

Strange.

**Comment by fiedl** [comment] 2017-03-05 10:57
Ah, I've found it:

The tests check for `Reply#attachments`, which also works for merged tickets and replies, because the [attachments override is handled here](https://github.com/fiedl/brimir/blob/d54397d8f71471c43fc91ce8bac0272cc2674c95/app/models/concerns/merged_reply.rb#L27L29).

But the view uses `Reply#attached_files`, not `Reply#attachments`:
https://github.com/fiedl/brimir/blob/d54397d8f71471c43fc91ce8bac0272cc2674c95/app/views/replies/_reply.html.erb#L56

Both, `Reply#attachments` and `Reply#attached_files` originally are defined here:
https://github.com/fiedl/brimir/blob/d54397d8f71471c43fc91ce8bac0272cc2674c95/app/models/concerns/email_message.rb#L21L24

@frenkel : Do you know why there are two associations, `#attachments` and `#attached_files`?

**Comment by frenkel** [comment] 2017-03-06 07:17
@fiedl Ah yes, that's probably it! The attached_file part is there because sometimes the attachments are embedded in the email, for example images. These are shown in the content instead of as seperate attachment. This are attachments with a filled `content_id`.

**Comment by fiedl** [comment] 2017-03-06 08:01
To be on the safe side, you could add some tests for `#attached_files`. But I've posted the quick fix here: https://github.com/ivaldi/brimir/pull/350

**Closed** 2017-03-06 09:36 UTC
