### ISSUE TITLE
email notifications all sent to the same address

### ISSUE THREAD

**Issue by georgebarbarosie** [ivaldi/brimir#279] opened 2016-06-02 09:54 UTC
WhenWhen an agent responds to a ticket that was opened by a customer, even though the notification field lists 
```
A notification was sent to the following addresses:
customer@domain.com
Agents:
agent1@company.com
agent2@company.com
agent3@company.com
```

the email notification gets sent 4 times to the same address, the email address of the customer. We've looked in the mail server's logs directly and see four separate emails queued but all four have the same destination (customer@domain.com).

We're using Brimir 0.7.0 and config.action_mailer.delivery_method is set to ":sendmail" (the default, I believe)

EDIT: The Brimir logs also show:
```
Sent mail to customer@domain.com (49.8ms)
I, [2016-06-02T11:40:23.383301 #30013]  INFO -- :
Sent mail to customer@domain.com (46.9ms)
I, [2016-06-02T11:40:23.432198 #30013]  INFO -- :
Sent mail to customer@domain.com (48.5ms)
I, [2016-06-02T11:40:23.478732 #30013]  INFO -- :
Sent mail to customer@domain.com (46.1ms)
```

**Comment by frenkel** [comment] 2016-06-02 10:02
That's an annoying problem. Did you set up custom email-addresses? Also, how does the params line after the POST look in your logs?

**Comment by georgebarbarosie** [comment] 2016-06-02 11:12
Oh I see what the problem may be.

We have indeed set up custom email addresses, moreover I've deleted (from the UI) the first email address and added it back again. If there is any assumption in the code that the default email address should have the Id 1 then that assumption has been broken when I've done this operation.

We have 6 email addresses in the system, the IDs they have are 2 to 7.

The following shows in the brimir logs right before the emails are sent:

```
I, [2016-06-02T11:40:23.137041 #30013]  INFO -- : Started POST "/replies" for 109.99.169.148 at 2016-06-02 11:40:23 +0200
I, [2016-06-02T11:40:23.139942 #30013]  INFO -- : Processing by RepliesController#create as HTML
I, [2016-06-02T11:40:23.140101 #30013]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"oIVYh4SP8YQqHF7IC5jcf8Z2rY9+
hQwi/c1BW5RPdKZjkIS+4yrRNTY4ZjjyEydoI4WR1XyC6dRrwcenpVFoug==", "reply"=>{"content_type"=>"html", "ticket_id"=>"105", "internal"=>
"false", "ticket_attributes"=>{"to_email_address_id"=>"7", "id"=>"105", "status"=>"open"}, "notified_user_ids"=>["", "9", "4", "8
", "6"], "content"=>"<p>&nbsp;test reply</p>\r\n<p><br />On June 02, 2016 12:39, customer@domain.com wrote:<br />&gt; test issue <br/></p>", "draft"=>"false"}}
```

email addresses in the users table are as follows:
```
 id |                 email                 | agent
----+---------------------------------------+-------
  4 | agent@company.com                     | t
  6 | customer@domain.com                   | f
  8 | agent2@company.com                    | t
  9 | agent3@company.com                    | t
(4 rows)
```

Email address 7 is the email_addresses table is the one that we added last with the same details as the default email address we deleted:

```
-[ RECORD 1 ]------+-----------------------------
id                 | 7
email              | helpdesk@company.com
default            | t
created_at         | 2016-05-31 13:21:30.290667
updated_at         | 2016-05-31 13:21:31.512613
verification_token |
name               | Company Helpdesk
```

**Comment by frenkel** [comment] 2016-06-02 11:23
There is no hardcoded id, so it can not be the problem. Using your log output and data tables it all looks correct to me. Have you set up any rules? Do the customer emails somehow end up in Brimir again?

**Comment by georgebarbarosie** [comment] 2016-06-02 11:48
We don't have any rules defined and there is no loopback to brimir (in this case at least -- I've seen that the system correctly identifies emails that end up back in brimir from notifications, and ignores them when the email addresses match). What got me thinking was the first entry in the notified_email_ids param of the POST (an empty string). Is that normal?

While testing this I've noticed this bug does not manifest when all the notified users are agents. It's only when there's at least one customer id in the notified users that this happens. All emails get sent to the last non-agent in the list; for example a POST on /replies with  param "notified_user_ids"=>["", "64", "9", "8", "62", "5"] has sent 5 identical emails to customer with ID 62.

When all user IDs are agents the correct email addresses are used.

**Comment by frenkel** [comment] 2016-06-03 12:07
Are you basing this report on the logs, or does the customer actually receive those mails? For customer mails we use the To: field in a special manner that the Rails logs apparently don't understand. We sent (in your example) 4 messages with 4 times the same To:, but in the smtp-envelope-to: field there are 4 differen email addresses. Could you verify that the customer also receives those 4 messages? If so, then the smtp-envelope-to: is apparently not working for your mail server. Are you using Postfix? Sendmail?

@fiedl Does my explanation seem plossible?

**Comment by georgebarbarosie** [comment] 2016-06-03 12:31
Hi,

I'm basing this report on the brimir logs, the mail server's logs as well as the customer's complaints. On one hand the customer receives the same message multiple times (depending on the number of notified_user_ids) and on the other the agents are not receiving the notifications. Also, in those cases where the bug is not manifesting the brimir logs show the correct email addresses in the lines beginning with "Sent mail to ", so these log entries look reliable to us.

I've managed to work around this issue on our install by changing line 112 of app/mailers/notification_mailer.rb (on HEAD I believe it's https://github.com/ivaldi/brimir/blob/master/app/mailers/notification_mailer.rb#L109), mail() call parameter "to: user.email", where current call parameter is "to: displayed_to_field".

I am really going out on a limb here (I have no experience with Ruby whatsoever) but smtp_envelope_to is probably not going to work if the mail delivery method is sendmail. If I get the chance to test this behaviour with config.action_mailer.delivery_method set to :smtp

**Comment by fiedl** [comment] 2016-06-03 12:59
I agree, @frenkel. This probably has something to do with the usage of `smtp_envelope_to`.

In production, we always use `:smtp` as delivery method, and `:letter_opener` in development. I don't have experience with `:sendmail`, yet.

As a first step, I would suggest to add additional logging to the production instance: Either somewhere near the [line of code @georgebarbarosie has suggested](https://github.com/ivaldi/brimir/blob/master/app/mailers/notification_mailer.rb#L109), or more permanently like this:

```ruby
# app/models/mail_message_extension.rb

# This is prepended to Mail::Message.
# https://github.com/mikel/mail/blob/master/lib/mail/message.rb
#
module MailMessageExtension

  def deliver
    Rails.logger.info "Sending mail smtp_envelope_to #{self.smtp_envelope_to.to_s}."
    return super
  end

end

# config/initializers/mail_message_extension.rb
Mail::Message.send(:prepend, MailMessageExtension)
```

**Comment by frenkel** [comment] 2016-06-03 13:15
I'm also using :sendmail in production for our hosted Brimir instances. These use Postfix. @georgebarbarosie what mail server are you using? The original Sendmail, or something else?

**Comment by georgebarbarosie** [comment] 2016-06-03 13:16
I'm running postfix 3.0.3

**Comment by frenkel** [comment] 2016-06-03 13:19
I'm using Postfix 2.9.6, so it's either a configuration issue, or a bug somewhere in Brimir. Could you add the logging as suggested by @fiedl?

**Comment by georgebarbarosie** [comment] 2016-06-03 14:01
My non-existent experience with Ruby is taking it's toll, I'm afraid. I've added both files as requested (app/models/mail_message_extension.rb and config/initializers/mail_message_extension.rb) but after restarting the application server I get this fatal error in the server logs:

```
/home/tripsol/htdocs/brimir/config/initializers/mail_message_extension.rb:1:in `<top (required)>': uninitialized constant Mail (NameError)
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib64/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
        from /usr/lib64/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib64/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib64/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
        from /usr/lib64/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib64/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
        from /usr/lib64/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/lib64/ruby/2.0.0/tsort.rb:180:in `each'
        from /usr/lib64/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/lib64/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/tripsol/htdocs/brimir/vendor/bundle/ruby/2.0.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
        from /home/tripsol/htdocs/brimir/config/environment.rb:5:in `<top (required)>'
        from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from config.ru:3:in `block in <main>'
        from /home/tripsol/.gem/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /home/tripsol/.gem/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /home/tripsol/.gem/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /home/tripsol/.gem/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /home/tripsol/.gem/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
```

I will try adding logging inside the new_reply method of NotificationMailer but I will have to wait until off-peak hours, probably during the weekend.

**Comment by fiedl** [comment] 2016-06-03 15:08
I'm trying this out and sending a pull request to add the logging. But I've got to grab a cup of coffee first ☕

**Comment by fiedl** [comment] 2016-06-03 17:42
I've opened this pull request to get the additional logging in brimir directly:
https://github.com/ivaldi/brimir/pull/280

There was a `require 'mail'` missing to get rid of "uninitialized constant Mail (NameError)".

With this modification, the log should look like this:

```
Sending mail smtp_envelope_to foo@example.com.

Sent mail to bar@example.com (18.5ms)
Date: Fri, 03 Jun 2016 19:34:04 +0200
From: support@localhost
To: bar@example.com
Message-ID: <5751bf8c86323_72003fe27d59ba38848d@fiedl-mbp.mail>
In-Reply-To: <5751bf134fa40_71473fc2f9feaf50133c2@fiedl-mbp.mail>
References: <5751b84152147_63de3fdd3ee4be74794dc@fiedl-mbp.mail>
 <5751bac0d4250_6d353ff308098aa435474@fiedl-mbp.mail>
 <5751bb3c8a679_6d353ff2fd8155303578a@fiedl-mbp.mail>
 <5751bb73e6920_6dad3ff2eb743c2c418d9@fiedl-mbp.mail>
 <5751bcc5ba78c_6f453fe218e13978513ab@fiedl-mbp.mail>
 <5751bd3768210_6fc83fc46f5306d8586e9@fiedl-mbp.mail>
 <5751bdd084549_6fc83fc470861f7c58913@fiedl-mbp.mail>
 <5751be3a28d19_6fc83fc46c7a368459296@fiedl-mbp.mail>
 <5751be55a01d6_706a3feff17a2a1c3804f@fiedl-mbp.mail>
 <5751bf134fa40_71473fc2f9feaf50133c2@fiedl-mbp.mail>
Subject: New reply: test
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5751bf8ccc2e0_72003fe27d59ba3885038";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
smtp-envelope-to: foo@example.com
```

**Comment by frenkel** [comment] 2016-06-04 07:41
@georgebarbarosie I've just merged those changes in `master`. Could you update your Brimir install to `master` and try again? It'll help us debug your problem.

**Comment by alexh089** [comment] 2016-07-09 18:31
@frenkel: I have a similar problem. When a new ticket gets assigned to a agent, the customer gets four times the same email. 

"AGENT XYZ will handle your support ticket."


Any ideas why this is happening?

production.log: 

I, [2016-07-09T20:23:15.622382 #5050]  INFO -- :   Rendered notification_mailer/new_reply.text.erb (1.0ms)
D, [2016-07-09T20:23:15.624626 #5050] DEBUG -- :
NotificationMailer#new_reply: processed outbound mail in 10.0ms
I, [2016-07-09T20:23:15.699304 #5050]  INFO -- :

**Comment by frenkel** [comment] 2016-07-11 06:01
Yes, it seems to have to do with the usage of smtp-envelope-to. Your mail server doesn't appear to support it, while ours (and @fiedl's) does.

**Comment by fiedl** [comment] 2016-07-19 10:53
Apparently, it has nothing to do with the mail server, but with the interaction between [rails](https://github.com/rails/rails) and the [mail gem](https://github.com/mikel/mail).

After some time-consuming digging and isolated tests using a [test application](https://github.com/fiedl/smtp_envelope_send_test), I've reported [the issue](https://github.com/mikel/mail/issues/1015).

In fact, our production server is affected as well and we had no complains for some time only because modern mail clients filter duplicates very well. @frenkel, if you want to try it out with your own smtp server, follow the [couple of steps described in test app's README](https://github.com/fiedl/smtp_envelope_send_test).

Until the issue is resolved in the mail gem, there is a [workaround](https://github.com/fiedl/smtp_envelope_send_test#workaround):

We basically have to insert a line that manually sets the `smtp_envelope_to` in brimir:

```ruby
recipients = %w(test1@example.com test2@example.com)
recipients.each do |recipient|
  mail = FooMailer.foo_mail(to: recipients, smtp_envelope_to: recipient)
  mail.smtp_envelope_to = recipient  # <---- INSERT THIS LINE
  mail.deliver
end
```

In fact, I should have realized this earlier, as [this line in the tests](https://github.com/ivaldi/brimir/blob/master/test/controllers/replies_controller_test.rb#L109) works only if asked for `mail.header_fields.select { |field| field.name == 'smtp-envelope-to' }`, where it should also work for `mail.smtp_envelope_to` directly . In fact, the header field `smtp-envelope-to` is ignored by the mail servers. They only look at the real smtp envelope.

**Comment by frenkel** [comment] 2016-07-19 15:18
None of our customers reported issues on our hosted Brimir instances, but maybe none of them CC agent's or other people. Anyways, I've merged your pull request.

**Closed** 2016-07-19 15:18 UTC
